---
# create a file in the home directory to test Semaphore setup
- name: Testing Semaphore
  hosts: hosts # test inventory lives on Semaphore right now
  become: yes
  become_method: sudo

  tasks:
    - name: Create file in home directory
      file:
        path: "~/semaphore-was-here.txt"
        state: touch

    - name: Create the user 'semaphore'
      #become: true
      #become_method: sudo
      # creating user without login shell or password
      user:
        name: semaphore
        shell: /sbin/nologin
        create_home: no
        comment: "test, nologin user"
